# Here you can specify default options for TinyMCE across all controllers
#
# theme: advanced
# plugins:
#  - table
#  - fullscreen
theme: advanced
mode: textareas
plugins:
  - paste
theme_advanced_buttons3_add: "pastetext, pasteword, selectall"
paste_auto_cleanup_on_paste: true
paste_convert_headers_to_strong: true