# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#   
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Major.create(:name => 'Daley', :city => cities.first)


BetaKey.find_or_create_by_beta_key("cs999")

['Under 5 feet', '5 feet - 5 feet 6 inches', '5 feet 6 inches - 6 feet', 'Over 6 feet'].each do |height|
  Height.find_or_create_by_text(height)
end

['Skinny', 'Average', 'Muscular', 'Athletic', 'A Few Extra Pounds', 'Thin', 'Petite', 'Curvy'].each do |built|
  Built.find_or_create_by_text(built)
end

['Asian', 'Black', 'Caucasian', 'Hispanic', 'Indian', 'Native American', 'Pacific Islander', 'Other'].each do |ethnicity|
  Ethnicity.find_or_create_by_text(ethnicity)
end

['English', 'Arabic', 'Chinese', 'Dutch', 'French', 'German', 'Italian', 'Japanese', 'Korean', 'Spanish',  'Other'].each do |language|
  Language.find_or_create_by_text(language)
end

['High School', 'College', 'Graduate Degree', 'PhD', 'Other'].each do |education|
  Education.find_or_create_by_text(education)
end

['Advertising', 'Architect', 'Arts', 'Consulting', 'Engineer', 'Finance', 'Health Care', 'Legal', 'Marketing', 'Sales', 'Technology', 'Self Employed', 'Student', 'Other'].each do |occupation|
  Occupation.find_or_create_by_text(occupation)
end
 
# ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Puerto Rico', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'Washington D.C.', 'West Virginia', 'Wisconsin', 'Wyoming'].each do |state|
#   State.find_or_create_by_state(state)
# end

["NYC Upcoming Event", "Richmond Upcoming Event", "Anything", "Art Event", "Bar Games", "Brunch/Lunch", "Club/Lounge", "Dinner", "Drinks", "House Party", "Just Hang Out", "Live Music", "Movie", "Museum", "Play A Sport", "Play Date for Kids", "Play Date for Pets", "Poetry/Prose", "Religious", "Sporting Event"].each_with_index do |interest, index|
  rs = Interest.find_or_create_by_text(interest)
  rs.update_attribute(:sort_id, index)
end

['Any/Multiple', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'].each do |week|
  Day.find_or_create_by_text(week)
end

['9AM - 1PM', '1PM - 5PM', '5PM - 10PM', 'After 10PM'].each do |availability|
  Availability.find_or_create_by_text(availability)
end

City.create(:name => "New York", :state => "New York", :abbrev => "New York City, NY")
City.create(:name => "Abilene", :state => "Texas", :abbrev => "Abilene, TX")
City.create(:name => "Akron", :state => "Ohio", :abbrev => "Akron, OH")
City.create(:name => "Albuquerque", :state => "New Mexico", :abbrev => "Albuquerque, NM")
City.create(:name => "Alexandria", :state => "Virginia", :abbrev => "Alexandria, VA")
City.create(:name => "Allentown", :state => "Pennsylvania", :abbrev => "Allentown, PA")
City.create(:name => "Amarillo", :state => "Texas", :abbrev => "Amarillo, TX")
City.create(:name => "Anaheim", :state => "California", :abbrev => "Anaheim, CA")
City.create(:name => "Anchorage", :state => "Alaska", :abbrev => "Anchorage, AK")
City.create(:name => "Ann Arbor", :state => "Michigan", :abbrev => "Ann Arbor, MI")
City.create(:name => "Antioch", :state => "California", :abbrev => "Antioch, CA")
City.create(:name => "Arlington", :state => "Texas", :abbrev => "Arlington, TX")
City.create(:name => "Arlington", :state => "Virginia", :abbrev => "Arlington, VA")
City.create(:name => "Arvada", :state => "Colorado", :abbrev => "Arvada, CO")
City.create(:name => "Athens", :state => "Georgia", :abbrev => "Athen, GA")
City.create(:name => "Atlanta", :state => "Georgia", :abbrev => "Atlanta, GA")
City.create(:name => "Augusta", :state => "Georgia", :abbrev => "August, GA")
City.create(:name => "Aurora", :state => "Colorado", :abbrev => "Aurora, CO")
City.create(:name => "Aurora", :state => "Illinois", :abbrev => "Aurora, IL")
City.create(:name => "Austin", :state => "Texas", :abbrev => "Austin, TX")
City.create(:name => "Bakersfield", :state => "California", :abbrev => "Bakersfield, CA")
City.create(:name => "Baltimore", :state => "Maryland", :abbrev => "Baltimore, MD")
City.create(:name => "Baton Rouge", :state => "Louisiana", :abbrev => "Baton Rouge, LA")
City.create(:name => "Beaumont", :state => "Texas", :abbrev => "Beaumont, TX")
City.create(:name => "Bellevue", :state => "Washington", :abbrev => "Bellevue, WA")
City.create(:name => "Berkeley", :state => "California", :abbrev => "Berkeley, CA")
City.create(:name => "Billings", :state => "Montana", :abbrev => "Billings, MT")
City.create(:name => "Birmingham", :state => "Alabama", :abbrev => "Birmingham, AL")
City.create(:name => "Boise", :state => "Idaho", :abbrev => "Boise, ID")
City.create(:name => "Boston", :state => "Massachusetts", :abbrev => "Boston, MA")
City.create(:name => "Bridgeport", :state => "Connecticut", :abbrev => "Bridgeport, CT")
City.create(:name => "Brownsville", :state => "Texas", :abbrev => "Brownsville, TX")
City.create(:name => "Buffalo", :state => "New York", :abbrev => "Buffalo, NY")
City.create(:name => "Burbank", :state => "California", :abbrev => "Cambridge, CA")
City.create(:name => "Cambridge", :state => "Massachusetts", :abbrev => "Cambridge, MA")
City.create(:name => "Cape Coral", :state => "Florida", :abbrev => "Cape Coral, FL")
City.create(:name => "Carlsbad", :state => "California", :abbrev => "Carlsbad, CA")
City.create(:name => "Carrollton", :state => "Texas", :abbrev => "Carrollton, TX")
City.create(:name => "Cary", :state => "North Carolina", :abbrev => "Cary, NC")
City.create(:name => "Cedar Rapids", :state => "Iowa", :abbrev => "Cedar Rapids, IA")
City.create(:name => "Centennial", :state => "Colorado", :abbrev => "Centennial, CO")
City.create(:name => "Chandler", :state => "Arizona", :abbrev => "Chandler, AZ")
City.create(:name => "Charleston", :state => "South Carolina", :abbrev => "Charleston, SC")
City.create(:name => "Charlotte", :state => "North Carolina", :abbrev => "Charlotte, NC")
City.create(:name => "Chattanooga", :state => "Tennessee", :abbrev => "Chattanooga, TN")
City.create(:name => "Chesapeake", :state => "Virginia", :abbrev => "Chesapeake, VA")
City.create(:name => "Chicago", :state => "Illinois", :abbrev => "Chicago, IL")
City.create(:name => "Chula Vista", :state => "California", :abbrev => "Chula Vista, CA")
City.create(:name => "Cincinnati", :state => "Ohio", :abbrev => "Cincinnati, OH")
City.create(:name => "Clarksville", :state => "Tennessee", :abbrev => "Clarsville, TN")
City.create(:name => "Clearwater", :state => "Florida", :abbrev => "Clearwater, FL")
City.create(:name => "Cleveland", :state => "Ohio", :abbrev => "Cleveland, OH")
City.create(:name => "Colorado Springs", :state => "Colorado", :abbrev => "Colorado Springs, CO")
City.create(:name => "Columbia, South Carolina", :state => "South Carolina", :abbrev => "Columbia, SC")
City.create(:name => "Columbia, Missouri", :state => "Missouri", :abbrev => "Columbia, MS")
City.create(:name => "Columbus, Ohio", :state => "Ohio", :abbrev => "Columbus, OH")
City.create(:name => "Columbus, Georgia", :state => "Georgia", :abbrev => "Columbus, GA")
City.create(:name => "Concord", :state => "California", :abbrev => "Concord, CA")
City.create(:name => "Coral Springs", :state => "Florida", :abbrev => "Coral Springs, FL")
City.create(:name => "Corona", :state => "California", :abbrev => "Corona, CA")
City.create(:name => "Corpus Christi", :state => "Texas", :abbrev => "Corpus Christi, TX")
City.create(:name => "Costa Mesa", :state => "California", :abbrev => "Costa Mesa, CA")
City.create(:name => "Dallas", :state => "Texas", :abbrev => "Dallas, TX")
City.create(:name => "Daly City", :state => "California", :abbrev => "Daly City, CA")
City.create(:name => "Dayton", :state => "Ohio", :abbrev => "Dayton, OH")
City.create(:name => "Denton", :state => "Texas", :abbrev => "Denton, TX")
City.create(:name => "Denver", :state => "Colorado", :abbrev => "Denver, CO")
City.create(:name => "Des Moines", :state => "Iowa", :abbrev => "Des Moines, IA")
City.create(:name => "Detroit", :state => "Michigan", :abbrev => "Detroit, MI")
City.create(:name => "Downey", :state => "California", :abbrev => "Downey, CA")
City.create(:name => "Durham", :state => "North Carolina", :abbrev => "Durham, NC")
City.create(:name => "El Monte", :state => "California", :abbrev => "El Monte, CA")
City.create(:name => "El Paso", :state => "Texas", :abbrev => "El Paso, TX")
City.create(:name => "Elgin", :state => "Illinois", :abbrev => "Elgin, TX")
City.create(:name => "Elizabeth", :state => "New Jersey", :abbrev => "Elizabeth, NJ")
City.create(:name => "Elk Grove", :state => "California", :abbrev => "Elk Grove, CA")
City.create(:name => "Erie", :state => "Pennsylvania", :abbrev => "Erie, PA")
City.create(:name => "Escondido", :state => "California", :abbrev => "Escondido, CA")
City.create(:name => "Eugene", :state => "Oregon", :abbrev => "Eugene, OR")
City.create(:name => "Evansville", :state => "Indiana", :abbrev => "Evansville, IN")
City.create(:name => "Everett", :state => "Washington", :abbrev => "Everett, WA")
City.create(:name => "Fairfield", :state => "California", :abbrev => "Fairfield, CA")
City.create(:name => "Fargo", :state => "North Dakota", :abbrev => "Fargo, ND")
City.create(:name => "Fayetteville", :state => "North Carolina", :abbrev => "Fayetteville, NC")
City.create(:name => "Flint", :state => "Michigan", :abbrev => "Flint, MI")
City.create(:name => "Fontana", :state => "California", :abbrev => "Fontana, CA")
City.create(:name => "Fort Collins", :state => "Colorado", :abbrev => "Fort Collins, CO")
City.create(:name => "Fort Lauderdale", :state => "Florida", :abbrev => "Fort Lauderdale, FL")
City.create(:name => "Fort Wayne", :state => "Indiana", :abbrev => "Fort Wayne, IN")
City.create(:name => "Fort Worth", :state => "Texas", :abbrev => "Fort Worth, TX")
City.create(:name => "Fremont", :state => "California", :abbrev => "Fremont, CA")
City.create(:name => "Fresno", :state => "California", :abbrev => "Fresno, CA")
City.create(:name => "Frisco", :state => "Texas", :abbrev => "Frisco, TX")
City.create(:name => "Fullerton", :state => "California", :abbrev => "Fullerton, CA")
City.create(:name => "Gainesville", :state => "Florida", :abbrev => "Gainsville, FL")
City.create(:name => "Garden Grove", :state => "California", :abbrev => "Garden Grove, CA")
City.create(:name => "Garland", :state => "Texas", :abbrev => "Garland, TX")
City.create(:name => "Gilbert", :state => "Arizona", :abbrev => "Gilbert, AZ")
City.create(:name => "Glendale", :state => "Arizona", :abbrev => "Glendale, AZ")
City.create(:name => "Glendale", :state => "California", :abbrev => "Glendale, CA")
City.create(:name => "Grand Prairie", :state => "Texas", :abbrev => "Grand Praire, TX")
City.create(:name => "Grand Rapids", :state => "Michigan", :abbrev => "Grand Rapids, MI")
City.create(:name => "Green Bay", :state => "Wisconsin", :abbrev => "Green Bay, WI")
City.create(:name => "Greensboro", :state => "North Carolina", :abbrev => "Greensboro, NC")
City.create(:name => "Gresham", :state => "Oregon", :abbrev => "Gresham, OR")
City.create(:name => "Hampton", :state => "Virginia", :abbrev => "Hampton, VA")
City.create(:name => "Hartford", :state => "Connecticut", :abbrev => "Hartford, CT")
City.create(:name => "Hayward", :state => "California", :abbrev => "Hayward, CA")
City.create(:name => "Henderson", :state => "Nevada", :abbrev => "Henderson, NV")
City.create(:name => "Hialeah", :state => "Florida", :abbrev => "Hialeah, FL")
City.create(:name => "High Point", :state => "North Carolina", :abbrev => "High Point, NC")
City.create(:name => "Hollywood", :state => "Florida", :abbrev => "Hollywood, FL")
City.create(:name => "Honolulu", :state => "Hawaii", :abbrev => "Honolulu, HI")
City.create(:name => "Houston", :state => "Texas", :abbrev => "Houston, TX")
City.create(:name => "Huntington Beach", :state => "California", :abbrev => "Huntingon Beach, CA")
City.create(:name => "Huntsville", :state => "Alabama", :abbrev => "Huntsville, AL")
City.create(:name => "Independence", :state => "Missouri", :abbrev => "Independence, MS")
City.create(:name => "Indianapolis", :state => "Indiana", :abbrev => "Indianapolis, IN")
City.create(:name => "Inglewood", :state => "California", :abbrev => "Inglewood, CA")
City.create(:name => "Irvine", :state => "California", :abbrev => "Irvine, CA")
City.create(:name => "Irving", :state => "Texas", :abbrev => "Irving, TX")
City.create(:name => "Jackson", :state => "Mississippi", :abbrev => "Jackson, MS")
City.create(:name => "Jacksonville", :state => "Florida", :abbrev => "Jacksonville, FL")
City.create(:name => "Jersey City", :state => "New Jersey", :abbrev => "Jersey City, NJ")
City.create(:name => "Joliet", :state => "Illinois", :abbrev => "Joliet, IL")
City.create(:name => "Kansas City, Missouri", :state => "Missouri", :abbrev => "Kansas City, MS")
City.create(:name => "Kansas City, Kansas", :state => "Kansas", :abbrev => "Kansas City, KA")
City.create(:name => "Killeen", :state => "Texas", :abbrev => "Kileen, TX")
City.create(:name => "Knoxville", :state => "Tennessee", :abbrev => "Knoxville, TN")
City.create(:name => "Lafayette", :state => "Louisiana", :abbrev => "Lafayette, LA")
City.create(:name => "Lakewood", :state => "Colorado", :abbrev => "Lakewood, CO")
City.create(:name => "Lancaster", :state => "California", :abbrev => "Lancaster, CA")
City.create(:name => "Lansing", :state => "Michigan", :abbrev => "Lansing, MI")
City.create(:name => "Laredo", :state => "Texas", :abbrev => "Laredo, TX")
City.create(:name => "Las Vegas", :state => "Nevada", :abbrev => "Las Vegas, NV")
City.create(:name => "Lexington", :state => "Kentucky", :abbrev => "Lexington, KY")
City.create(:name => "Lincoln", :state => "Nebraska", :abbrev => "Lincoln, NE")
City.create(:name => "Little Rock", :state => "Arkansas", :abbrev => "Little Rock, AR")
City.create(:name => "Long Beach", :state => "California", :abbrev => "Long Beach, CA")
City.create(:name => "Los Angeles", :state => "California", :abbrev => "Los Angeles, CA")
City.create(:name => "Louisville", :state => "Kentucky", :abbrev => "Louisville, KY")
City.create(:name => "Lowell", :state => "Massachusetts", :abbrev => "Lowell, MA")
City.create(:name => "Lubbock", :state => "Texas", :abbrev => "Lubbock, TX")
City.create(:name => "Madison", :state => "Wisconsin", :abbrev => "Madison, WI")
City.create(:name => "Manchester", :state => "New Hampshire", :abbrev => "Manchester, NH")
City.create(:name => "McAllen", :state => "Texas", :abbrev => "McAllen, TX")
City.create(:name => "McKinney", :state => "Texas", :abbrev => "McKinney, TX")
City.create(:name => "Memphis", :state => "Tennessee", :abbrev => "Memphis, TN")
City.create(:name => "Mesa", :state => "Arizona", :abbrev => "Mesa, AZ")
City.create(:name => "Mesquite", :state => "Texas", :abbrev => "Mesquite, TX")
City.create(:name => "Miami", :state => "Florida", :abbrev => "Miami, FL")
City.create(:name => "Miami Gardens", :state => "Florida", :abbrev => "Miami Gardens, FL")
City.create(:name => "Midland", :state => "Texas", :abbrev => "Midland, TX")
City.create(:name => "Milwaukee", :state => "Wisconsin", :abbrev => "Milwauee, WI")
City.create(:name => "Minneapolis", :state => "Minnesota", :abbrev => "Minneapolis, MN")
City.create(:name => "Miramar", :state => "Florida", :abbrev => "Miramar, FL")
City.create(:name => "Mobile", :state => "Alabama", :abbrev => "Mobile, AL")
City.create(:name => "Modesto", :state => "California", :abbrev => "Modesto, CA")
City.create(:name => "Montgomery", :state => "Alabama", :abbrev => "Montgomery, AL")
City.create(:name => "Moreno Valley", :state => "California", :abbrev => "Moreno Valley, CA")
City.create(:name => "Murfreesboro", :state => "Tennessee", :abbrev => "Murfreesboro, TN")
City.create(:name => "Murrieta", :state => "California", :abbrev => "Murrieta, CA")
City.create(:name => "Naperville", :state => "Illinois", :abbrev => "Naperville, IL")
City.create(:name => "Nashville ", :state => "Tennessee", :abbrev => "Nashville, TN")
City.create(:name => "New Haven", :state => "Connecticut", :abbrev => "New Haven, CT")
City.create(:name => "New Orleans", :state => "Louisiana", :abbrev => "New Orleans, LA")
City.create(:name => "Newark", :state => "New Jersey", :abbrev => "Newark, NJ")
City.create(:name => "Newport News ", :state => "Virginia", :abbrev => "Newport News, VA")
City.create(:name => "Norfolk ", :state => "Virginia", :abbrev => "Norfolk, VA")
City.create(:name => "Norman", :state => "Oklahoma", :abbrev => "Norman, OK")
City.create(:name => "Norwalk", :state => "California", :abbrev => "Norwalk, CA")
City.create(:name => "Oakland", :state => "California", :abbrev => "Oakland, CA")
City.create(:name => "Oceanside", :state => "California", :abbrev => "Oceanside, CA")
City.create(:name => "Oklahoma City", :state => "Oklahoma", :abbrev => "Oklahoma City, OK")
City.create(:name => "Olathe", :state => "Kansas", :abbrev => "Olath, KS")
City.create(:name => "Omaha", :state => "Nebraska", :abbrev => "Omaha, NE")
City.create(:name => "Ontario, California", :state => "California", :abbrev => "Ontario, CA")
City.create(:name => "Orange", :state => "California", :abbrev => "Orange, CA")
City.create(:name => "Orlando", :state => "Florida", :abbrev => "Orlando, FL")
City.create(:name => "Overland Park", :state => "Kansas", :abbrev => "Overland Park, KS")
City.create(:name => "Oxnard", :state => "California", :abbrev => "Oxnard, CA")
City.create(:name => "Palm Bay", :state => "Florida", :abbrev => "Palm Bay, FL")
City.create(:name => "Palmdale", :state => "California", :abbrev => "Palmdale, CA")
City.create(:name => "Pasadena, Texas", :state => "Texas", :abbrev => "Pasadena, TX")
City.create(:name => "Pasadena, California", :state => "California", :abbrev => "Pasadena, CA")
City.create(:name => "Paterson", :state => "New Jersey", :abbrev => "Paterson, NJ")
City.create(:name => "Pembroke Pines", :state => "Florida", :abbrev => "Pembroke Pines, FL")
City.create(:name => "Peoria", :state => "Arizona", :abbrev => "Peoria, AZ")
City.create(:name => "Peoria", :state => "Illinois", :abbrev => "Peoria, IL")
City.create(:name => "Philadelphia", :state => "Pennsylvania", :abbrev => "Philadelphia, PA")
City.create(:name => "Phoenix", :state => "Arizona", :abbrev => "Phoenix, AZ")
City.create(:name => "Pittsburgh", :state => "Pennsylvania", :abbrev => "Pittsburgh, PA")
City.create(:name => "Plano", :state => "Texas", :abbrev => "Plano, TX")
City.create(:name => "Pomona", :state => "California", :abbrev => "Pomona, CA")
City.create(:name => "Port St. Lucie", :state => "Florida", :abbrev => "Port St. Lucie, FL")
City.create(:name => "Portland", :state => "Oregon", :abbrev => "Portland, OR")
City.create(:name => "Providence", :state => "Rhode Island", :abbrev => "Providence, RI")
City.create(:name => "Provo", :state => "Utah", :abbrev => "Provo, UT")
City.create(:name => "Pueblo", :state => "Colorado", :abbrev => "Pueblo, CO")
City.create(:name => "Raleigh", :state => "North Carolina", :abbrev => "Raleigh, NC")
City.create(:name => "Rancho Cucamonga", :state => "California", :abbrev => "Rancho Cucamonga, CA")
City.create(:name => "Reno", :state => "Nevada", :abbrev => "Reno, NV")
City.create(:name => "Richmond", :state => "California", :abbrev => "Richmond, CA")
City.create(:name => "Richmond ", :state => "Virginia", :abbrev => "Richmond, VA")
City.create(:name => "Riverside", :state => "California", :abbrev => "Riverside, CA")
City.create(:name => "Rochester", :state => "New York", :abbrev => "Rochester, NY")
City.create(:name => "Rochester", :state => "Minnesota", :abbrev => "Rocherster, MN")
City.create(:name => "Rockford", :state => "Illinois", :abbrev => "Rockford, IL")
City.create(:name => "Roseville", :state => "California", :abbrev => "Roseville, CA")
City.create(:name => "Sacramento", :state => "California", :abbrev => "Sacramento, CA")
City.create(:name => "Salem", :state => "Oregon", :abbrev => "Salem, OR")
City.create(:name => "Salinas", :state => "California", :abbrev => "Salinas, CA")
City.create(:name => "Salt Lake City", :state => "Utah", :abbrev => "Salt Lake City, U")
City.create(:name => "San Antonio", :state => "Texas", :abbrev => "San Antonio, TX")
City.create(:name => "San Bernardino", :state => "California", :abbrev => "San Bernardino, CA")
City.create(:name => "San Diego", :state => "California", :abbrev => "San Diego, CA")
City.create(:name => "San Francisco", :state => "California", :abbrev => "San Francisco, CA")
City.create(:name => "San Jose", :state => "California", :abbrev => "San Jose, CA")
City.create(:name => "Santa Ana", :state => "California", :abbrev => "Santa Ana, CA")
City.create(:name => "Santa Clara", :state => "California", :abbrev => "Santa Clara, CA")
City.create(:name => "Santa Clarita", :state => "California", :abbrev => "Santa Clarita, CA")
City.create(:name => "Santa Rosa", :state => "California", :abbrev => "Santa Rosa, CA")
City.create(:name => "Savannah", :state => "Georgia", :abbrev => "Savannah, GA")
City.create(:name => "Scottsdale", :state => "Arizona", :abbrev => "Scottsdale, AZ")
City.create(:name => "Seattle", :state => "Washington", :abbrev => "Seattle, WA")
City.create(:name => "Shreveport", :state => "Louisiana", :abbrev => "Shreveport, LA")
City.create(:name => "Simi Valley", :state => "California", :abbrev => "Simi Valley, CA")
City.create(:name => "Sioux Falls", :state => "South Dakota", :abbrev => "Sioux Falls, SD")
City.create(:name => "South Bend", :state => "Indiana", :abbrev => "South Bend, IN")
City.create(:name => "Spokane", :state => "Washington", :abbrev => "Spokane, WA")
City.create(:name => "Springfield", :state => "Missouri", :abbrev => "Springfield, MS")
City.create(:name => "Springfield", :state => "Massachusetts", :abbrev => "Springfield, MA")
City.create(:name => "Springfield", :state => "Illinois", :abbrev => "Springfield, IL")
City.create(:name => "St. Louis [d]", :state => "Missouri", :abbrev => "St Louis, MS")
City.create(:name => "St. Paul", :state => "Minnesota", :abbrev => "St Paul, MN")
City.create(:name => "St. Petersburg", :state => "Florida", :abbrev => "St Petersburg, FL")
City.create(:name => "Stamford", :state => "Connecticut", :abbrev => "Stamford, CT")
City.create(:name => "Sterling Heights", :state => "Michigan", :abbrev => "Sterling Heights, MI")
City.create(:name => "Stockton", :state => "California", :abbrev => "Stockton, CA")
City.create(:name => "Sunnyvale", :state => "California", :abbrev => "Sunnyvale, CA")
City.create(:name => "Surprise", :state => "Arizona", :abbrev => "Surprise, AZ")
City.create(:name => "Syracuse", :state => "New York", :abbrev => "Syracuse, NY")
City.create(:name => "Tacoma", :state => "Washington", :abbrev => "Tacoma, WA")
City.create(:name => "Tallahassee", :state => "Florida", :abbrev => "Tallahasse, FL")
City.create(:name => "Tampa", :state => "Florida", :abbrev => "Tampa, FL")
City.create(:name => "Tempe", :state => "Arizona", :abbrev => "Tempe, AZ")
City.create(:name => "Thornton", :state => "Colorado", :abbrev => "Thornton, CO")
City.create(:name => "Thousand Oaks", :state => "California", :abbrev => "Thousand Oaks, CA")
City.create(:name => "Toledo", :state => "Ohio", :abbrev => "Toledo, OH")
City.create(:name => "Topeka", :state => "Kansas", :abbrev => "Topeka, KS")
City.create(:name => "Torrance", :state => "California", :abbrev => "Torrance, CA")
City.create(:name => "Tucson", :state => "Arizona", :abbrev => "Tucson, AZ")
City.create(:name => "Tulsa", :state => "Oklahoma", :abbrev => "Tulsa, OK")
City.create(:name => "Vallejo", :state => "California", :abbrev => "Vallejo, CA")
City.create(:name => "Vancouver", :state => "Washington", :abbrev => "Vancouver, WA")
City.create(:name => "Ventura", :state => "California", :abbrev => "Ventura, CA")
City.create(:name => "Victorville", :state => "California", :abbrev => "Victorville, CA")
City.create(:name => "Virginia Beach ", :state => "Virginia", :abbrev => "Virginia Beach, VA")
City.create(:name => "Visalia", :state => "California", :abbrev => "Visalla, CA")
City.create(:name => "Waco", :state => "Texas", :abbrev => "Waco, TX")
City.create(:name => "Warren", :state => "Michigan", :abbrev => "Warren, MI")
City.create(:name => "Washington", :state => "District of Columbia", :abbrev => "Washington, DC")
City.create(:name => "Waterbury", :state => "Connecticut", :abbrev => "Waterbury, CT")
City.create(:name => "West Covina", :state => "California", :abbrev => "West Covina, CA")
City.create(:name => "West Jordan", :state => "Utah", :abbrev => "West Jordan, UR")
City.create(:name => "West Valley City", :state => "Utah", :abbrev => "West Valley City, UT")
City.create(:name => "Westminster", :state => "Colorado", :abbrev => "Westminister, CO")
City.create(:name => "Wichita", :state => "Kansas", :abbrev => "Wichita, KS")
City.create(:name => "Wichita Falls", :state => "Texas", :abbrev => "Wichita Falls, TX")
City.create(:name => "Wilmington", :state => "North Carolina", :abbrev => "Wilmington, NC")
City.create(:name => "Winston-Salem", :state => "North Carolina", :abbrev => "Winston-Salem, NC")
City.create(:name => "Worcester", :state => "Massachusetts", :abbrev => "Worcester, MA")
City.create(:name => "Yonkers", :state => "New York", :abbrev => "Yonkers, NY")
City.create(:name => "Toronto", :abbrev => "Toronto, Canada")
City.create(:name => "Montreal", :abbrev => "Montreal, Canada")
City.create(:name => "Quebec City", :abbrev => "Quebec City, Canada")
City.create(:name => "Ottawa, Canada", :abbrev => "Ottawa, Canada")
City.create(:name => "Vancouver, Canada", :abbrev => "Vancouver, Canada")
City.create(:name => "Calgary", :abbrev => "Calgary, Canada")

image = File.new("#{Rails.root}/public/images/connectingsexes-logo.png")

Admin.create(:image => image, :username => 'admin', :email => 'do-not-reply@connectingsexes.com', :password => 'admin', :password_confirmation => 'admin', :name => 'Administrator', :save_password => 'admin')
Admin.create(:image => image, :username => 'evostyle', :email => 'do-not-reply@evostyle.com', :password => 'evostyle', :password_confirmation => 'evostyle', :name => 'The Style Girlfriend - evostyle.com', :save_password => 'evostyle', :blogger => true)
Admin.create(:image => image, :username => 'fashionindie', :email => 'do-not-reply@fashionindie.com', :password => 'fashionindie', :password_confirmation => 'fashionindie', :name => 'FashionIndie.com', :save_password => 'fashionindie', :blogger => true)
Admin.create(:image => image, :username => 'supertrainerrick', :email => 'do-not-reply@supertrainerrick.com', :password => 'supertrainerrick', :password_confirmation => 'supertrainerrick', :name => 'Super Trainer Rick', :save_password => 'supertrainerrick', :blogger => true)
Admin.create(:image => image, :username => 'talesfromthedate', :email => 'do-not-reply@talesfromthedate.com', :password => 'talesfromthedate', :password_confirmation => 'talesfromthedate', :name => 'TALES FROM THE DATE', :save_password => 'talesfromthedate', :blogger => true)
Admin.create(:image => image, :username => 'music', :email => 'do-not-reply@music.com', :password => 'music', :password_confirmation => 'music', :blogger => 1, :save_password => 'music', :name => 'Music')
Admin.create(:image => image, :username => 'events', :email => 'do-not-reply@events.com', :password => 'events', :password_confirmation => 'events', :blogger => 1, :save_password => 'events', :name => 'Events')
Admin.create(:image => image, :username => 'lifestyle', :email => 'do-not-reply@lifestyle.com', :password => 'lifestyle', :password_confirmation => 'lifestyle', :blogger => 1, :save_password => 'lifestyle', :name => 'Lifestyle')
Admin.create(:image => image, :username => 'localcelebrity', :email => 'do-not-reply@localcelebrity.com', :password => 'localcelebrity', :password_confirmation => 'localcelebrity', :blogger => 1, :save_password => 'localcelebrity', :name => 'Local Celebrity')

TagLine.create(:name => 'Make Friends Before The Party')